routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::get('address/ajax','AddressController@ajax')->name('address.ajax');
	Route::resource('address', 'AddressController');

	Route::get('profile','UserController@viewProfile')->name('profile.view');
	Route::post('profile','UserController@updateProfile')->name('profile.update');
});

app/Models/Addressbook.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Addressbook extends Model
{
    public $timestamps = true;

    protected $table = "address_book";
    protected $fillable = [
    	'title', 'name', 'number', 'address_line_1', 'address_line_2', 'address_line_3', 'pincode',
    	'city_slug', 'state_slug', 'country_slug', 'status', 'is_default', 'type'
    ];
    protected $hidden = [
        'created_at', 'updated_at',
    ];

    public static function addRules(){
    	return [
    		'title'=>'required|max:30|min:2',
            'name'=>'required|max:30|min:2',
            'number'=>'required|digits:10',
            'address_line_1'=>'required|min:5|max:50',
            'address_line_2'=>'required|min:2|max:50',
            'address_line_3'=>'max:50',
            'pincode'=>'required|digits:6',
            'city_slug'=>'required',
            'state_slug'=>'required',
            'country_slug'=>'required',
            'is_default'=>'in:1,0',
            'type'=>'required|in:from,to',
    	];
    }

    public static function editRules(){
    	return [
    		'title'=>'required|max:30|min:2',
            'name'=>'required|max:30|min:2',
            'number'=>'required|digits:10',
            'address_line_1'=>'required|min:5|max:50',
            'address_line_2'=>'required|min:2|max:50',
            'address_line_3'=>'max:50',
            'pincode'=>'required|digits:6',
            'city_slug'=>'required',
            'state_slug'=>'required',
            'country_slug'=>'required',
            'is_default'=>'in:1,0',
            'type'=>'required|in:from,to',
    	];
    }

    public static function removeDefaults($user_id,$type){
        return static::where([
            ['is_default','=',1],
            ['type','=',$type]
        ])->update(['is_default' => 0]);
    }
}

resources/views/addressbook/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <div style="display: inline;"><b>Manage Address Book</b></div>
                    <div style="float: right">
                        <button class="btn btn-xs btn-primary" type="submit" form="base-form" href="{{route('address.create')}}">Save</button>
                    </div>
                </div>

                <div class="card-body">
                    {!! Form::open(['route' => 'address.store','id' => 'base-form']) !!}
                        @include('addressbook.partials.form')
                    {!! Form::close() !!} 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-css')
    
@endsection

@section('page-js')
    <script type="text/javascript">

    </script>
@endsection

resources/views/addressbook/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <div style="display: inline;"><b>Manage Address Book</b></div>
                    <div style="float: right">
                        <button class="btn btn-xs btn-primary" type="submit" form="base-form">Save</button>
                    </div>
                </div>

                <div class="card-body">
                    {!! Form::open(['route' => ['address.update',$address],'method' => 'PUT','id' => 'base-form']) !!}
                        @include('addressbook.partials.form')
                    {!! Form::close() !!} 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-css')
    
@endsection

@section('page-js')
    <script type="text/javascript">

    </script>
@endsection

resources/views/addressbook/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div style="display: inline;"><b>Manage Address Book</b></div>
                    <div style="float: right">
                        <a class="btn btn-xs btn-primary" href="">Add</a>
                    </div>
                </div>

                <div class="card-body">
                    <table id="table" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Name</th>
                                <th>Number</th>
                                <th>Address</th>
                                <th>Default</th>
                                <th>Type</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Title</th>
                                <th>Name</th>
                                <th>Number</th>
                                <th>Address</th>
                                <th>Default</th>
                                <th>Type</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-css')
    <link rel="stylesheet" type="text/css" href="{{ asset('plugin/datatable/dataTables.bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('plugin/font-awesome/font-awesome.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('plugin/datatable/jquery.dataTables.min.css') }}">
@endsection

@section('page-js')
    <script type="text/javascript" src="{{ asset('plugin/datatable/jquery.dataTables.min.js') }}"></script>
    <script>
        var ajaxUrl = '{!! route("address.ajax") !!}';
        $(function() {
            var dataColumns = [
                {data: 'title', name: 'title'},
                {data: 'name', name: 'name'},
                {data: 'number', name: 'number'},
                {data: 'address', name: 'address'},
                {data: 'default', name: 'default'},
                {data: 'type', name: 'type'},
                {data: 'actions', name: 'actions', orderable: false, searchable: false}
            ];
            dataTableInit('#table', dataColumns, ajaxUrl);
        });
        function confirmDelete(){
            return confirm("Are you sure you want to delete address!");
        }
    </script>
@endsection